#this engine.py is responsible for the detection of the agent. It will be used to detect the agent in the system and report it to the user.

from agent.detect import rules

SET_OF_RULES = [
    rules.rule_unknown_executable,
    rules.rule_new_destination,
    rules.rule_high_bandwidth,
    rules.rule_idle_process_activity,
    rules.rule_repeated_connections,
]

def run_detection(record):
    """
    Runs all detection rules against the given record and collects any alerts.
    
    Args:
        record (dict): A dictionary containing process and network activity information.
        
    Returns:
        list: A list of alerts generated by the detection rules.
    """
    alerts = []
    
    for rule in SET_OF_RULES:
        try:
            alert = rule(record)
        except Exception:
            # A single rule should not break the detection pipeline.
            continue

        # Only accept None or a mapping-like alert dict
        if not alert:
            continue

        if not isinstance(alert, dict):
            continue

        alerts.append({
            "timestamp": record.get("timestamp"),
            "process_name": record.get("process_name"),
            "pid": record.get("pid"),
            "exe": record.get("exe"),
            "rule": alert.get("rule"),
            "severity": alert.get("severity"),
            "reason": alert.get("reason"),
        })
    
    return alerts