#this is for creating models using sqllite for storing agent data

#this table is for storing network connection data
# Use IF NOT EXISTS so tables are not recreated unexpectedly on startup
CONNECTION_TABLE = """
CREATE TABLE IF NOT EXISTS connections (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp REAL,
    pid INTEGER,
    process_name TEXT,
    exe TEXT,
    username TEXT,
    create_time REAL,
    local_ip TEXT,
    local_port INTEGER,
    remote_ip TEXT,
    remote_port INTEGER,
    protocol TEXT,
    status TEXT,
    bytes_sent INTEGER,
    bytes_recv INTEGER
);
"""
#this table is for storing bandwidth summary data
BANDWIDTH_TABLE =  """
CREATE TABLE IF NOT EXISTS bandwidth_summary (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp REAL,
    pid INTEGER,
    process_name TEXT,
    exe TEXT,
    bytes_sent INTEGER,
    bytes_recv INTEGER,
    interval REAL
);
"""

# this table is for storing alerts generated by the detection rules

ALERT_TABLE = """
CREATE TABLE IF NOT EXISTS alerts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp REAL,
    pid INTEGER,
    process_name TEXT,
    exe TEXT,
    rule TEXT,
    severity TEXT,
    reason TEXT
);
"""